-- Strip variants schema (#397 caregiver viewer + #398 external co-parent viewer).
--
-- Two additions, both gated on the design bundle dropped into
-- docs/design-handoffs/strip-variants/. Read that README for the full
-- product framing; this migration is the data model.
--
--   (1) households.default_brief_items — jsonb array of "things the
--       caregiver should hand back to the next parent" items. The strip
--       turns its countdown chip alert-tinted when the caregiver has
--       open brief tasks AND the next hand-off is within ~2h. Brief
--       tasks themselves are generated by an edge function (Phase G,
--       follow-up #489); for now, just the column.
--
--       Shape: `[{ "label": string }, ...]`. Kept loose so the schema
--       doesn't pin the design before the auto-task generator lands.
--
--   (2) child_external_coparents — per-kid junction linking a profile
--       to a child as their external co-parent. The external parent is
--       NOT a household_member (they have no role inside the household);
--       they have a per-kid relationship instead. One profile can be
--       external to kids across different households. The strip's
--       per-kid POV framing (#398) reads this table to:
--         • discover which kids the viewer is external to
--         • render the viewer's identity color on the kid's strip
--
--       RLS is the careful part: the external profile sees ONLY their
--       own row + the kids they're linked to (via child_external_coparents
--       and a permissive carve-out on `children`). Household parents
--       manage the rows for their household's kids.
--
-- Both changes are additive — no backfill, no downstream code yet.

-- ─── (1) households.default_brief_items ─────────────────────────────────

alter table public.households
    add column if not exists default_brief_items jsonb
        not null default '[]'::jsonb
        check (jsonb_typeof(default_brief_items) = 'array');

comment on column public.households.default_brief_items is
    'Caregiver hand-off brief items. Auto-generates brief tasks on hand-off days (#397). Shape: [{label: string}, ...].';

-- ─── (2) child_external_coparents ───────────────────────────────────────

create table if not exists public.child_external_coparents (
    child_id uuid not null references public.children (id) on delete cascade,
    profile_id uuid not null references public.profiles (id) on delete cascade,
    -- Identity color the external co-parent renders with on this kid's
    -- strip (the dashed busy-block row, the 7-day bar's "external" side).
    -- Stored hex; the strip falls back to a stable palette pick when null.
    color text,
    created_at timestamptz not null default now(),
    primary key (child_id, profile_id)
);

create index if not exists child_external_coparents_profile_idx
    on public.child_external_coparents (profile_id);

alter table public.child_external_coparents enable row level security;

-- Helper: resolve a child's household_id (for RLS). SECURITY DEFINER
-- avoids the recursive RLS check on `children` from within child_*
-- policies. Same pattern as the other resolver helpers in 0002.
create or replace function public.household_id_for_child(p_child_id uuid)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
    select household_id from public.children where id = p_child_id
$$;

-- SELECT: the external profile reads their own rows; household parents
-- + members read all rows for kids in their household. The two cases
-- have to be OR'd because the external profile is NOT a member.
create policy "child_external_coparents read self or household"
    on public.child_external_coparents for select
    using (
        profile_id = auth.uid()
        or public.is_household_member(public.household_id_for_child(child_id))
    );

-- INSERT/UPDATE/DELETE: household parents only. External parents can't
-- add themselves; the household has to invite them (Phase G+ follow-up
-- once an invite flow lands — for now rows are created server-side or
-- by direct admin action).
create policy "child_external_coparents write parents"
    on public.child_external_coparents for insert
    with check (
        public.is_household_parent(public.household_id_for_child(child_id))
    );

create policy "child_external_coparents update parents"
    on public.child_external_coparents for update
    using (
        public.is_household_parent(public.household_id_for_child(child_id))
    )
    with check (
        public.is_household_parent(public.household_id_for_child(child_id))
    );

create policy "child_external_coparents delete parents"
    on public.child_external_coparents for delete
    using (
        public.is_household_parent(public.household_id_for_child(child_id))
    );

-- Carve-out on `children`: an external co-parent must be able to read
-- the child row for any kid they're linked to (display name, color,
-- birthdate for age). Without this, the per-kid POV framing breaks —
-- the strip resolves `child.display_name` and gets null.
--
-- The existing `children` policies are member-scoped; this is purely
-- additive (an OR on top of the member check via a new policy).
create policy "children read external coparent"
    on public.children for select
    using (
        exists (
            select 1 from public.child_external_coparents cec
            where cec.child_id = public.children.id
              and cec.profile_id = auth.uid()
        )
    );

-- Same carve-out on `custody_schedules` so the read-only viewer can
-- resolve hand-off times + the pattern for any kid they're external to.
-- They don't get to see the whole household — but they need the
-- schedule row to compute next-handoff for THEIR linked kids.
create policy "custody_schedules read external coparent"
    on public.custody_schedules for select
    using (
        exists (
            select 1 from public.child_external_coparents cec
            join public.children c on c.id = cec.child_id
            where c.household_id = public.custody_schedules.household_id
              and cec.profile_id = auth.uid()
        )
    );

-- Same carve-out on `custody_overrides` for resolver correctness on
-- the external viewer's strip (an override on the kid's household date
-- has to be visible or the strip lies about who has the kid).
create policy "custody_overrides read external coparent"
    on public.custody_overrides for select
    using (
        exists (
            select 1 from public.child_external_coparents cec
            join public.children c on c.id = cec.child_id
            where c.household_id = public.custody_overrides.household_id
              and cec.profile_id = auth.uid()
              -- Per-child overrides: external parent only sees overrides
              -- on kids they're actually linked to (or whole-household
              -- overrides, which affect all kids).
              and (
                  public.custody_overrides.child_id is null
                  or public.custody_overrides.child_id = cec.child_id
              )
        )
    );
